name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    container: 
      image: docker.io/paveldroo/go-ogg-packer:base

    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v4

    # - name: Install APT packages
    #   run: |
    #     apt-get update
    #     apt-get install -y --no-install-recommends libopus-dev=1.3.1-3 libopusfile-dev=0.12-4

    # - name: Install Taskfile
    #   run: go install github.com/go-task/task/v3/cmd/task@v3.9.1

    # - name: Task Test
    #   run: task docker-test

    - name: Task Test
      run: cd /app && task test

    # - name: Test
    #   run: go test -v ./...
